AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to deploy EC2 instance

Parameters:
  InstanceType:
    Description: EC2 Instance Type
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
  MyIpAddress:
    Description: My IP Address
    Type: String
    Default: 82.35.77.174/32
    MinLength: "9"
    MaxLength: "18"
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.    
  #
  # Using System Manager Public Parameters as aliases to get the AMI ID
  # https://aws.amazon.com/blogs/compute/using-system-manager-parameter-as-an-alias-for-ami-id/
  #
  ImageId:
    Description: Amazon Linux 2023 AMI ImageId (eu-north-1)
    #Type: String
    #Default: ami-0368b2c10d7184bc7
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

Resources:
  sshKey:
    Type: "AWS::EC2::KeyPair"
    Properties:
      KeyName: sshKeyForEC2
      KeyFormat: pem # pem|ppk 
      KeyType: ed25519 # rsa|ed25519

  ec2DefaultSecurityGroup:
    #
    # AWS::EC2::SecurityGroup Reference
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-securitygroup.html
    #
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: ec2-default-security-group
      GroupDescription: Default EC2 security group allows incoming ssh access
      SecurityGroupIngress:
        - CidrIp: !Ref MyIpAddress #either one must be defined CidrIp, CidrIpv6, SourcePrefixListId, SourceSecurityGroupId
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
      #VpcId: #Skip this one to use default VPC

  ec2Instance:
    #
    # AWS::EC2::Instance Reference
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html
    #
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      KeyName: !Ref sshKey
      SecurityGroupIds:
        - !Ref ec2DefaultSecurityGroup
      Tags:
        - Key: "Name"
          Value: "ec2-instance"

Outputs:
  sshKeyPairId:
    Value: !GetAtt sshKey.KeyPairId

  sshKeyFingerprint:
    Value: !GetAtt sshKey.KeyFingerprint

  EC2InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref ec2Instance

  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value: !GetAtt ec2Instance.PublicDnsName

  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt ec2Instance.PublicIp